language: python

python:
- '3.5'

env:
  - TRAVIS_NODE_VERSION="6.9.1"
    MEERKAT_FRONTEND_SETTINGS="/home/travis/build/meerkat-code/meerkat_frontend/country_config/null_config.py"
    MEERKAT_AUTH_SETTINGS="/home/travis/build/meerkat-code/meerkat_frontend/meerkat_auth/auth.cfg"

install:
- pip install .
- pip install -r .travis-requirements.txt
# As per http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install -g yarn bower gulp
- npm update -g yarn
- yarn cache clean
- yarn install
- git clone https://github.com/meerkat-code/meerkat_auth.git
- pip install -r meerkat_auth/requirements.txt

before_script:
- export PYTHONPATH=$HOME/build/meerkat-code/meerkat_frontend/meerkat_auth/meerkat_auth
- bower install
- gulp

script: nosetests

notifications:
  slack:
    secure: JAyJidj1nalEoJhp7JL22tabEXn1xBl6MXQOnP6pratbVyz/haWuDh7OQGZxf0kXO1zaKu6k9A4zQZKr0LiKeUT1Xx5kdeP8C9NzZrYtf6IKLw50HhTq7OhnQ9PtdR2DQ+uT1PcudQWNOeq8+0Yu3aTD/nBH626Gp7qQqRhuX3vUYZs1V05mmxbIrND2OtjR69UkIWwnzFzJDsJCbjY5PojPtfQ1lDlXwulkNV66RfJnJYeWf0ndBgCnEff6OXJ993oUcCWHEsQP5HdgR2IEnyuXHzgjiAnc+M6C4Xes/uS1FEOlwVvpkvysx+FvbQl+SEet+9ottakp5P8QjSKG4159L0Po3n2AISfIcZgMSVuCkIF9mHl23vo8Sb0LdoliHSZhbRP05spAioxf0cfBLBa3isMV2Ur7/BhHjc9Tjxs+obLdJmPRzcch1bYWePFDVJySA57nZUR0CdvObl0h+he+ye5z9/MkfRvHN+kUXkOb5tI+CY1n76vjqoVT6AUagA3Vpsn8Q3dQKhd4JmXg70NeEgM9M0Msql2TDCtEVvk47twEQrlQXCOjGU1B/JJ9l98qQdF3YkuS1vSbjXXZnFYHDg0M6vSddmFhVADfflATbM2pU7v7jdBpTbJxL9rz75Lf535Dk0haM1IWeafmnZhrddq5qrj5+qqsFHmA/ww=
